package com.astro.entity.InventoryModule;

import lombok.Data;

import javax.persistence.*;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Data
@Table(name = "goods_receipt_inspection")
public class GoodsReceiptInspection {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "receipt_inspection_no", nullable = false, unique = true)
    private String receiptInspectionNo;

    @Column(name = "installation_date")
    private LocalDate installationDate;

    @Column(name = "commissioning_date")
    private LocalDate commissioningDate;

    @Column(name = "asset_code", nullable = false, unique = true)
    private String assetCode;

    @Column(name = "additional_material_description")
    private String additionalMaterialDescription;

    @Column(name = "locator", nullable = false)
    private String locator;

    @Column(name = "print_label_option", columnDefinition = "BOOLEAN DEFAULT false")
    private boolean printLabelOption;

    @Column(name = "depreciation_rate", precision = 5, scale = 2)
    private double depreciationRate;


 //   private double bookValue;  //autogenerated value

    @Column(name = "attach_component_popup")
    private String attachComponentPopup;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdDate = LocalDateTime.now();
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedDate = LocalDateTime.now();





}
